services:
  proxy:
    image: nginx:latest
    container_name: unified-proxy
    network_mode: host
    ports:
      - "8080:8080"
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped